{% set name = "pigar" %}
{% set version = "0.9.1" %}
{% set sha256 = "039a779accafee334b2d84f2391ea4cd0eb84bc419cd8437bc67cb4a910a0a77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/damnever/pigar/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pigar = pigar.__main__:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - colorama >=0.3.9
    - requests >=2.20.0
    - futures            # [py2k]

test:
  imports:
    - pigar
  commands:
    - pigar --help

about:
  home: https://github.com/damnever/pigar
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fantastic tool to generate requirements for your Python project, and more
    than that.

extra:
  recipe-maintainers:
    - jakirkham
