travis:
  secure:
    BINSTAR_TOKEN: AIs9doiAoS2jp90l/aGIb7SiKM3llDtlrGvOuXGTY0kEVQluCRERNobyge3MqPfZjd+h9NsNXsk0sfwfsYgy6Maho+3VcoyCvL/RQoZXNQZvSUbXfl5EZaoUje3/ZZl7SeUHa20mBevq0YhLIlhl3Rd+MUCnhtvzV0WgParkjdhhZ/21kj/Kc+KGbcRap4g9oogLNTAQNB7vshbcPpuaC4mcPNFQcpL6KhyIIlgho5HEB+350SmuQByycQk/WWQFrre40pWBFiS4wFj1tIs8Ny/yCy9Bb99i/D04VJOUWCF3JyWRPFD8Qdmo3XdTbQt6ax8kcQ/lCMnT///JkKUlvj6m040rvprgSDUgz5KsEdztAqXoz5kXRF8wNH9BbN2K/carNrf83jYkct2nYVcg6eYbxcpAqs8OocYVEyeRSh83C4JABwjP6w65AyvQl6NnjsFQD9+fnnv6RCclmOG1KV7lpCO1621hS+HnQoDCBEeslo5aGOyHwjmEGU0+tscKala62PvcUrUjXduBR+uoPCifTw99c1B1SwuIVosvbscVT8S13VZ32/bgCtEV9I+64JZvMvRS9ikpE+cjvhHdNS3sAXrFrPsNS0fY/E1lGyQ+k89WJGMBzm9QzxrTHsHQDajSC+TKeHhJYm2SApcQajZg4ddrDr4TRbVy8wgOnXY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
